# Generated by Django 2.2 on 2020-11-27 15:06

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articlepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/', verbose_name='标题图'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='如：文学,诗歌,青春', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
    ]
