# Generated by Django 2.2 on 2020-12-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20201202_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100, verbose_name='摘要'),
        ),
    ]
