# Generated by Django 2.2 on 2020-12-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20201202_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
    ]
