# Generated by Django 2.2 on 2020-12-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20201208_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name': '栏目', 'verbose_name_plural': '栏目'},
        ),
    ]
