# Generated by Django 2.2 on 2020-12-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20201208_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='excerpt',
        ),
    ]
