# Generated by Django 2.2 on 2021-06-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_articlecollect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecollect',
            name='artcle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticlePost', verbose_name='文章'),
        ),
    ]
