# Generated by Django 2.2 on 2021-06-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20210624_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecollect',
            name='artcle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticlePost', verbose_name='收藏文章'),
        ),
    ]
