# Generated by Django 2.2 on 2021-06-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20210624_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name': '类别管理', 'verbose_name_plural': '类别管理'},
        ),
    ]
