# Generated by Django 2.2 on 2021-06-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_articlecollect_unique_iden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecollect',
            name='unique_iden',
        ),
    ]
