# Generated by Django 2.2 on 2020-11-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201127_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户扩展', 'verbose_name_plural': '用户扩展'},
        ),
    ]
