# Generated by Django 2.2 on 2020-11-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20201127_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '扩展信息', 'verbose_name_plural': '扩展信息'},
        ),
    ]
