# Generated by Django 2.2 on 2020-12-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20201127_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '扩展', 'verbose_name_plural': '扩展'},
        ),
    ]
