# Generated by Django 2.2 on 2020-12-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20201208_2008'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='tb_userprofile',
        ),
    ]
