# Generated by Django 2.2 on 2020-11-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20201127_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='tb_comment',
        ),
    ]
